site_name: Nextedy WORKSHEET
site_description: 'Interactive Work Tracking and Team Assignments for Polarion ALM.'
site_author: Nextedy
site_url: https://worksheet.nextedy.com

nav:
    - Home: index.md
    - Download: download.md
    - Pricing: pricing.md 
    - Support: support.md 
    - News: news.md
    - About: about.md

theme:
  name: 'material'
  font: false
  palette:
    primary: 'black'
    accent: 'green'
  favicon: img/favicon.png
  custom_dir: 'theme'
  logo: 'https://www.nextedy.com/wp-content/uploads/2018/10/nextedy-logo.png'

extra_css:
  - 'extra/extra.css'

extra_javascript:
  - 'extra/extra.js'
  
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - tables
  - attr_list
  
copyright: 'Copyright &copy; 2020 Nextedy Systems'
  