site_name: Nextedy WORKSHEET
site_description: 'Interactive Work Tracking and Team Assignments for Polarion ALM.'
site_author: Nextedy
site_url: https://worksheet.nextedy.com

nav:
    - Home: index.md
    - Download: download.md
    - Pricing: pricing.md 
    - Support: support.md 
    - News: news.md
    - About: about.md

theme:
  name: 'material'
  font: false
  palette:
    primary: 'black'
    accent: 'green'
  favicon: img/favicon.png
  custom_dir: 'theme'
  logo: 'https://www.nextedy.com/wp-content/uploads/2018/10/nextedy-logo.png'

extra_css:
  - 'extra/extra.css'

extra_javascript:
  - 'extra/extra.js'
  
extra:
  product:
     name: Nextedy WORKSHEET
     url: https://worksheet.nextedy.com 
     requirements: Polarion 18.1 and newer   
  support:
     solution: 48000448935
     installGuide: https://nextedy.freshdesk.com/support/solutions/articles/48000973428-nextedy-worksheet-installation-guide 
  hs:
     id: 6265870
     quoteFormId: 208fa80c-333b-4347-a303-afa5199f70e7
     downloadFormId: 7bbfe403-1d5c-48fb-9e82-4bdcc46c7e4f
  
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - tables
  - attr_list
  
plugins:
    - search
    - markdownextradata: {}  
  
copyright: 'Copyright &copy; 2020 Nextedy Systems'
  